// ─── English → Korean INN Ingredient Mapping ─────────────────────────────────
// Source: MFDS INN 목록, WHO INN, 식약처 의약품 성분 한글명
// Coverage: ~400 common drug ingredients

export const INN_KO: Record<string, string> = {
  // ── NSAIDs / 진통소염제 ──────────────────────────────────────────────────
  "ASPIRIN": "아스피린",
  "ACETYLSALICYLIC ACID": "아세틸살리실산",
  "IBUPROFEN": "이부프로펜",
  "NAPROXEN": "나프록센",
  "DICLOFENAC": "디클로페낙",
  "CELECOXIB": "셀레콕시브",
  "INDOMETHACIN": "인도메타신",
  "MELOXICAM": "멜록시캄",
  "PIROXICAM": "피록시캄",
  "KETOPROFEN": "케토프로펜",
  "KETOROLAC": "케토롤락",
  "MEFENAMIC ACID": "메페남산",
  "ETORICOXIB": "에토리콕시브",
  "SULINDAC": "술린닥",
  "ETODOLAC": "에토돌락",
  "LORNOXICAM": "로르녹시캄",
  "ACECLOFENAC": "아세클로페낙",
  "DEXIBUPROFEN": "덱시부프로펜",
  "FLURBIPROFEN": "플루르비프로펜",
  "OXAPROZIN": "옥사프로진",

  // ── Analgesics / 해열진통제 ─────────────────────────────────────────────
  "ACETAMINOPHEN": "아세트아미노펜",
  "PARACETAMOL": "파라세타몰",
  "TRAMADOL": "트라마돌",
  "CODEINE": "코데인",
  "MORPHINE": "모르핀",
  "OXYCODONE": "옥시코돈",
  "HYDROCODONE": "하이드로코돈",
  "FENTANYL": "펜타닐",
  "BUPRENORPHINE": "부프레노르핀",
  "NALOXONE": "날록손",
  "NALTREXONE": "날트렉손",
  "TAPENTADOL": "타펜타돌",
  "MEPERIDINE": "메페리딘",
  "PETHIDINE": "페티딘",
  "PENTAZOCINE": "펜타조신",

  // ── Statins / 고지혈증 ──────────────────────────────────────────────────
  "ATORVASTATIN": "아토르바스타틴",
  "SIMVASTATIN": "심바스타틴",
  "ROSUVASTATIN": "로수바스타틴",
  "PRAVASTATIN": "프라바스타틴",
  "LOVASTATIN": "로바스타틴",
  "FLUVASTATIN": "플루바스타틴",
  "PITAVASTATIN": "피타바스타틴",
  "CERIVASTATIN": "세리바스타틴",
  "EZETIMIBE": "에제티미브",
  "FENOFIBRATE": "페노피브레이트",
  "GEMFIBROZIL": "겜피브로질",
  "BEZAFIBRATE": "베자피브레이트",
  "NIACIN": "니코틴산",
  "CHOLESTYRAMINE": "콜레스티라민",
  "EVOLOCUMAB": "에볼로쿠맙",
  "ALIROCUMAB": "알리로쿠맙",

  // ── ACE Inhibitors / ACE 억제제 ─────────────────────────────────────────
  "LISINOPRIL": "리시노프릴",
  "ENALAPRIL": "에날라프릴",
  "RAMIPRIL": "라미프릴",
  "CAPTOPRIL": "캅토프릴",
  "PERINDOPRIL": "페린도프릴",
  "FOSINOPRIL": "포시노프릴",
  "BENAZEPRIL": "베나제프릴",
  "QUINAPRIL": "퀴나프릴",
  "TRANDOLAPRIL": "트란돌라프릴",
  "MOEXIPRIL": "모엑시프릴",
  "ZOFENOPRIL": "조페노프릴",
  "CILAZAPRIL": "실라자프릴",
  "IMIDAPRIL": "이미다프릴",
  "DELAPRIL": "델라프릴",

  // ── ARBs / 안지오텐신 수용체 차단제 ─────────────────────────────────────
  "LOSARTAN": "로사르탄",
  "VALSARTAN": "발사르탄",
  "IRBESARTAN": "이르베사르탄",
  "CANDESARTAN": "칸데사르탄",
  "OLMESARTAN": "올메사르탄",
  "TELMISARTAN": "텔미사르탄",
  "EPROSARTAN": "에프로사르탄",
  "AZILSARTAN": "아질사르탄",
  "FIMASARTAN": "피마사르탄",

  // ── Beta Blockers / 베타차단제 ──────────────────────────────────────────
  "METOPROLOL": "메토프롤롤",
  "ATENOLOL": "아테놀롤",
  "BISOPROLOL": "비소프롤롤",
  "CARVEDILOL": "카르베딜롤",
  "PROPRANOLOL": "프로프라놀롤",
  "NEBIVOLOL": "네비볼롤",
  "LABETALOL": "라베탈롤",
  "NADOLOL": "나돌롤",
  "TIMOLOL": "티몰롤",
  "ACEBUTOLOL": "아세부톨롤",
  "PINDOLOL": "핀돌롤",
  "BETAXOLOL": "베탁솔롤",
  "SOTALOL": "소탈롤",
  "CELIPROLOL": "셀리프롤롤",
  "METOPROLOL SUCCINATE": "메토프롤롤숙시네이트",
  "METOPROLOL TARTRATE": "메토프롤롤타르트레이트",

  // ── Calcium Channel Blockers / 칼슘채널차단제 ─────────────────────────
  "AMLODIPINE": "암로디핀",
  "NIFEDIPINE": "니페디핀",
  "DILTIAZEM": "딜티아젬",
  "VERAPAMIL": "베라파밀",
  "FELODIPINE": "펠로디핀",
  "NICARDIPINE": "니카르디핀",
  "NIMODIPINE": "니모디핀",
  "LERCANIDIPINE": "레르카니디핀",
  "LACIDIPINE": "라시디핀",
  "BARNIDIPINE": "바르니디핀",
  "CLEVIDIPINE": "클레비디핀",
  "ISRADIPINE": "이스라디핀",
  "MANIDIPINE": "마니디핀",

  // ── Proton Pump Inhibitors / 위산분비억제제 ─────────────────────────────
  "OMEPRAZOLE": "오메프라졸",
  "ESOMEPRAZOLE": "에소메프라졸",
  "LANSOPRAZOLE": "란소프라졸",
  "PANTOPRAZOLE": "판토프라졸",
  "RABEPRAZOLE": "라베프라졸",
  "DEXLANSOPRAZOLE": "덱스란소프라졸",
  "ILAPRAZOLE": "일라프라졸",
  "VONOPRAZAN": "보노프라잔",
  "TEGOPRAZAN": "테고프라잔",

  // ── H2 Blockers ─────────────────────────────────────────────────────────
  "RANITIDINE": "라니티딘",
  "FAMOTIDINE": "파모티딘",
  "CIMETIDINE": "시메티딘",
  "NIZATIDINE": "니자티딘",
  "ROXATIDINE": "록사티딘",

  // ── Antidiabetics / 당뇨병 치료제 ──────────────────────────────────────
  "METFORMIN": "메트포르민",
  "GLIPIZIDE": "글리피지드",
  "GLYBURIDE": "글리부리드",
  "GLIBENCLAMIDE": "글리벤클라미드",
  "GLIMEPIRIDE": "글리메피리드",
  "PIOGLITAZONE": "피오글리타존",
  "ROSIGLITAZONE": "로시글리타존",
  "SITAGLIPTIN": "시타글립틴",
  "SAXAGLIPTIN": "삭사글립틴",
  "VILDAGLIPTIN": "빌다글립틴",
  "ALOGLIPTIN": "알로글립틴",
  "LINAGLIPTIN": "리나글립틴",
  "EMPAGLIFLOZIN": "엠파글리플로진",
  "DAPAGLIFLOZIN": "다파글리플로진",
  "CANAGLIFLOZIN": "카나글리플로진",
  "ERTUGLIFLOZIN": "에르투글리플로진",
  "EXENATIDE": "엑세나티드",
  "LIRAGLUTIDE": "리라글루티드",
  "SEMAGLUTIDE": "세마글루티드",
  "DULAGLUTIDE": "둘라글루티드",
  "LIXISENATIDE": "릭시세나티드",
  "INSULIN": "인슐린",
  "INSULIN GLARGINE": "인슐린글라르진",
  "INSULIN ASPART": "인슐린아스파르트",
  "INSULIN LISPRO": "인슐린리스프로",
  "INSULIN DETEMIR": "인슐린데테미르",
  "ACARBOSE": "아카르보스",
  "REPAGLINIDE": "레파글리니드",
  "NATEGLINIDE": "나테글리니드",

  // ── Antidepressants / 항우울제 ─────────────────────────────────────────
  "FLUOXETINE": "플루옥세틴",
  "SERTRALINE": "설트랄린",
  "PAROXETINE": "파록세틴",
  "CITALOPRAM": "시탈로프람",
  "ESCITALOPRAM": "에스시탈로프람",
  "FLUVOXAMINE": "플루복사민",
  "VENLAFAXINE": "벤라팍신",
  "DULOXETINE": "둘록세틴",
  "DESVENLAFAXINE": "데스벤라팍신",
  "MIRTAZAPINE": "미르타자핀",
  "BUPROPION": "부프로피온",
  "TRAZODONE": "트라조돈",
  "AMITRIPTYLINE": "아미트립틸린",
  "NORTRIPTYLINE": "노르트립틸린",
  "IMIPRAMINE": "이미프라민",
  "CLOMIPRAMINE": "클로미프라민",
  "DOXEPIN": "독세핀",
  "MAPROTILINE": "마프로틸린",
  "MOCLOBEMIDE": "모클로베미드",
  "AGOMELATINE": "아고멜라틴",
  "MILNACIPRAN": "밀나시프란",
  "LEVOMILNACIPRAN": "레보밀나시프란",

  // ── Antipsychotics / 항정신병약 ─────────────────────────────────────────
  "OLANZAPINE": "올란자핀",
  "RISPERIDONE": "리스페리돈",
  "QUETIAPINE": "쿠에티아핀",
  "ARIPIPRAZOLE": "아리피프라졸",
  "ZIPRASIDONE": "지프라시돈",
  "CLOZAPINE": "클로자핀",
  "AMISULPRIDE": "아미설프리드",
  "HALOPERIDOL": "할로페리돌",
  "CHLORPROMAZINE": "클로르프로마진",
  "PALIPERIDONE": "팔리페리돈",
  "LURASIDONE": "루라시돈",
  "ASENAPINE": "아세나핀",
  "BREXPIPRAZOLE": "브렉스피프라졸",
  "CARIPRAZINE": "카리프라진",
  "ILOPERIDONE": "일로페리돈",

  // ── Anticoagulants / 항응고제 ───────────────────────────────────────────
  "WARFARIN": "와파린",
  "HEPARIN": "헤파린",
  "ENOXAPARIN": "에녹사파린",
  "DABIGATRAN": "다비가트란",
  "RIVAROXABAN": "리바록사반",
  "APIXABAN": "아픽사반",
  "EDOXABAN": "에독사반",
  "FONDAPARINUX": "폰다파리눅스",
  "PHENPROCOUMON": "펜프로쿠몬",
  "ACENOCOUMAROL": "아세노쿠마롤",

  // ── Antiplatelet / 항혈소판제 ────────────────────────────────────────────
  "CLOPIDOGREL": "클로피도그렐",
  "TICAGRELOR": "티카그렐러",
  "PRASUGREL": "프라수그렐",
  "TICLOPIDINE": "티클로피딘",
  "CILOSTAZOL": "실로스타졸",
  "DIPYRIDAMOLE": "디피리다몰",

  // ── Diuretics / 이뇨제 ─────────────────────────────────────────────────
  "HYDROCHLOROTHIAZIDE": "하이드로클로로티아지드",
  "FUROSEMIDE": "푸로세미드",
  "SPIRONOLACTONE": "스피로노락톤",
  "TORSEMIDE": "토르세미드",
  "CHLORTHALIDONE": "클로르탈리돈",
  "INDAPAMIDE": "인다파미드",
  "BUMETANIDE": "부메타니드",
  "EPLERENONE": "에플레레논",
  "TRIAMTERENE": "트리암테렌",
  "AMILORIDE": "아밀로리드",
  "METOLAZONE": "메톨라존",

  // ── Antibiotics / 항생제 ────────────────────────────────────────────────
  "AMOXICILLIN": "아목시실린",
  "AMPICILLIN": "암피실린",
  "PENICILLIN": "페니실린",
  "CEPHALEXIN": "세팔렉신",
  "CEFUROXIME": "세푸록심",
  "CEFIXIME": "세픽심",
  "CEFTRIAXONE": "세프트리악손",
  "CEFDINIR": "세프디니르",
  "CEFPODOXIME": "세프포독심",
  "CLINDAMYCIN": "클린다마이신",
  "AZITHROMYCIN": "아지스로마이신",
  "CLARITHROMYCIN": "클래리스로마이신",
  "ERYTHROMYCIN": "에리스로마이신",
  "DOXYCYCLINE": "독시사이클린",
  "TETRACYCLINE": "테트라사이클린",
  "CIPROFLOXACIN": "시프로플록사신",
  "LEVOFLOXACIN": "레보플록사신",
  "MOXIFLOXACIN": "목시플록사신",
  "TRIMETHOPRIM": "트리메토프림",
  "SULFAMETHOXAZOLE": "설파메톡사졸",
  "METRONIDAZOLE": "메트로니다졸",
  "TINIDAZOLE": "티니다졸",
  "NITROFURANTOIN": "니트로푸란토인",
  "LINEZOLID": "리네졸리드",
  "VANCOMYCIN": "반코마이신",
  "MEROPENEM": "메로페넴",
  "IMIPENEM": "이미페넴",
  "PIPERACILLIN": "피페라실린",
  "TAZOBACTAM": "타조박탐",
  "CLAVULANATE": "클라불란산",
  "CLAVULANIC ACID": "클라불란산",
  "SULBACTAM": "설박탐",
  "AMOXICILLIN CLAVULANATE": "아목시실린클라불란산칼륨",
  "RIFAMPICIN": "리팜피신",
  "ISONIAZID": "이소니아지드",
  "PYRAZINAMIDE": "피라진아미드",
  "ETHAMBUTOL": "에탐부톨",
  "STREPTOMYCIN": "스트렙토마이신",
  "GENTAMICIN": "겐타마이신",
  "TOBRAMYCIN": "토브라마이신",
  "AMIKACIN": "아미카신",
  "COLISTIN": "콜리스틴",
  "FOSFOMYCIN": "포스포마이신",
  "FIDAXOMICIN": "피닥소마이신",

  // ── Antifungals / 항진균제 ──────────────────────────────────────────────
  "FLUCONAZOLE": "플루코나졸",
  "ITRACONAZOLE": "이트라코나졸",
  "VORICONAZOLE": "보리코나졸",
  "POSACONAZOLE": "포사코나졸",
  "AMPHOTERICIN B": "암포테리신비",
  "CASPOFUNGIN": "카스포펀진",
  "MICAFUNGIN": "마이카펀진",
  "TERBINAFINE": "터비나핀",
  "KETOCONAZOLE": "케토코나졸",
  "CLOTRIMAZOLE": "클로트리마졸",
  "MICONAZOLE": "미코나졸",
  "NYSTATIN": "니스타틴",

  // ── Antivirals / 항바이러스제 ───────────────────────────────────────────
  "ACYCLOVIR": "아시클로비르",
  "VALACYCLOVIR": "발라시클로비르",
  "GANCICLOVIR": "간시클로비르",
  "VALGANCICLOVIR": "발간시클로비르",
  "OSELTAMIVIR": "오셀타미비르",
  "ZANAMIVIR": "자나미비르",
  "RIBAVIRIN": "리바비린",
  "TENOFOVIR": "테노포비르",
  "EMTRICITABINE": "엠트리시타빈",
  "LAMIVUDINE": "라미부딘",
  "EFAVIRENZ": "에파비렌즈",
  "LOPINAVIR": "로피나비르",
  "RITONAVIR": "리토나비르",
  "ATAZANAVIR": "아타자나비르",
  "DARUNAVIR": "다루나비르",
  "SOFOSBUVIR": "소포스부비르",
  "LEDIPASVIR": "레디파스비르",

  // ── Respiratory / 호흡기 치료제 ─────────────────────────────────────────
  "SALBUTAMOL": "살부타몰",
  "ALBUTEROL": "알부테롤",
  "SALMETEROL": "살메테롤",
  "FORMOTEROL": "포르모테롤",
  "INDACATEROL": "인다카테롤",
  "TIOTROPIUM": "티오트로피움",
  "IPRATROPIUM": "이프라트로피움",
  "FLUTICASONE": "플루티카손",
  "BUDESONIDE": "부데소니드",
  "BECLOMETHASONE": "베클로메타손",
  "MOMETASONE": "모메타손",
  "CICLESONIDE": "시클레소니드",
  "MONTELUKAST": "몬테루카스트",
  "ZAFIRLUKAST": "자피르루카스트",
  "THEOPHYLLINE": "테오필린",
  "ROFLUMILAST": "로플루밀라스트",
  "DEXTROMETHORPHAN": "덱스트로메토르판",
  "GUAIFENESIN": "구아이페네신",
  "ACETYLCYSTEINE": "아세틸시스테인",
  "ERDOSTEINE": "에르도스테인",
  "AMBROXOL": "암브록솔",
  "BROMHEXINE": "브롬헥신",

  // ── Thyroid / 갑상선 ────────────────────────────────────────────────────
  "LEVOTHYROXINE": "레보티록신",
  "LIOTHYRONINE": "리오티로닌",
  "METHIMAZOLE": "메티마졸",
  "PROPYLTHIOURACIL": "프로필티오우라실",

  // ── Hormones / 호르몬제 ─────────────────────────────────────────────────
  "ESTRADIOL": "에스트라디올",
  "ESTROGEN": "에스트로겐",
  "PROGESTERONE": "프로게스테론",
  "MEDROXYPROGESTERONE": "메드록시프로게스테론",
  "TESTOSTERONE": "테스토스테론",
  "DEXAMETHASONE": "덱사메타손",
  "PREDNISOLONE": "프레드니솔론",
  "PREDNISONE": "프레드니손",
  "METHYLPREDNISOLONE": "메틸프레드니솔론",
  "HYDROCORTISONE": "하이드로코르티손",
  "TRIAMCINOLONE": "트리암시놀론",
  "BETAMETHASONE": "베타메타손",
  "FLUDROCORTISONE": "플루드로코르티손",

  // ── Neurological / 신경계 ───────────────────────────────────────────────
  "GABAPENTIN": "가바펜틴",
  "PREGABALIN": "프레가발린",
  "CARBAMAZEPINE": "카르바마제핀",
  "VALPROIC ACID": "발프로산",
  "VALPROATE": "발프로에이트",
  "LAMOTRIGINE": "라모트리진",
  "LEVETIRACETAM": "레베티라세탐",
  "PHENYTOIN": "페니토인",
  "TOPIRAMATE": "토피라메이트",
  "OXCARBAZEPINE": "옥스카르바제핀",
  "ZONISAMIDE": "조니사미드",
  "CLONAZEPAM": "클로나제팜",
  "DIAZEPAM": "디아제팜",
  "ALPRAZOLAM": "알프라졸람",
  "LORAZEPAM": "로라제팜",
  "MIDAZOLAM": "미다졸람",
  "TEMAZEPAM": "테마제팜",
  "NITRAZEPAM": "니트라제팜",
  "ZOLPIDEM": "졸피뎀",
  "ESZOPICLONE": "에스조피클론",
  "DONEPEZIL": "도네페질",
  "RIVASTIGMINE": "리바스티그민",
  "GALANTAMINE": "갈란타민",
  "MEMANTINE": "메만틴",
  "LEVODOPA": "레보도파",
  "CARBIDOPA": "카르비도파",
  "PRAMIPEXOLE": "프라미펙솔",
  "ROPINIROLE": "로피니롤",
  "RASAGILINE": "라사길린",
  "SELEGILINE": "셀레길린",
  "AMANTADINE": "아만타딘",
  "SUMATRIPTAN": "수마트립탄",
  "RIZATRIPTAN": "리자트립탄",
  "ZOLMITRIPTAN": "졸미트립탄",

  // ── Cardiovascular / 심혈관계 ───────────────────────────────────────────
  "DIGOXIN": "디곡신",
  "AMIODARONE": "아미오다론",
  "FLECAINIDE": "플레카이니드",
  "PROPAFENONE": "프로파페논",
  "IVABRADINE": "이바브라딘",
  "RANOLAZINE": "라놀라진",
  "ISOSORBIDE MONONITRATE": "이소소르비드모노니트레이트",
  "ISOSORBIDE DINITRATE": "이소소르비드디니트레이트",
  "NITROGLYCERIN": "니트로글리세린",
  "NITROGLYCERINE": "니트로글리세린",
  "SILDENAFIL": "실데나필",
  "TADALAFIL": "타다라필",
  "VARDENAFIL": "바르데나필",

  // ── GI / 소화기계 ────────────────────────────────────────────────────────
  "LOPERAMIDE": "로페라미드",
  "ONDANSETRON": "온단세트론",
  "METOCLOPRAMIDE": "메토클로프라미드",
  "DOMPERIDONE": "돔페리돈",
  "BISACODYL": "비사코딜",
  "LACTULOSE": "락툴로스",
  "MESALAMINE": "메살라민",
  "MESALAZINE": "메살라진",
  "SULFASALAZINE": "설파살라진",
  "INFLIXIMAB": "인플릭시맙",
  "ADALIMUMAB": "아달리무맙",

  // ── Musculoskeletal / 근골격계 ──────────────────────────────────────────
  "ALLOPURINOL": "알로퓨리놀",
  "COLCHICINE": "콜히친",
  "FEBUXOSTAT": "페북소스타트",
  "ALENDRONATE": "알렌드로네이트",
  "RISEDRONATE": "리세드로네이트",
  "ZOLEDRONIC ACID": "졸레드론산",
  "IBANDRONATE": "이반드로네이트",
  "TERIPARATIDE": "테리파라티드",
  "DENOSUMAB": "데노수맙",
  "RALOXIFENE": "랄록시펜",
  "CYCLOBENZAPRINE": "사이클로벤자프린",
  "BACLOFEN": "바클로펜",
  "TIZANIDINE": "티자니딘",
  "METHOCARBAMOL": "메토카르바몰",
  "EPERISONE": "에페리손",

  // ── Immunology & Oncology / 면역·항암 ──────────────────────────────────
  "METHOTREXATE": "메토트렉세이트",
  "AZATHIOPRINE": "아자티오프린",
  "CYCLOSPORINE": "사이클로스포린",
  "TACROLIMUS": "타크로리무스",
  "MYCOPHENOLATE": "마이코페놀레이트",
  "HYDROXYCHLOROQUINE": "하이드록시클로로퀸",
  "CHLOROQUINE": "클로로퀸",
  "LEFLUNOMIDE": "레플루노미드",
  "IMATINIB": "이마티닙",
  "ERLOTINIB": "에를로티닙",
  "GEFITINIB": "게피티닙",
  "TAMOXIFEN": "타목시펜",
  "LETROZOLE": "레트로졸",
  "ANASTROZOLE": "아나스트로졸",
  "EXEMESTANE": "엑세메스탄",

  // ── Vitamins & Supplements / 비타민·보조제 ─────────────────────────────
  "ASCORBIC ACID": "아스코르브산",
  "VITAMIN C": "비타민씨",
  "TOCOPHEROL": "토코페롤",
  "VITAMIN E": "비타민이",
  "CHOLECALCIFEROL": "콜레칼시페롤",
  "VITAMIN D": "비타민디",
  "VITAMIN D3": "비타민디3",
  "CALCITRIOL": "칼시트리올",
  "FOLIC ACID": "엽산",
  "FOLATE": "폴레이트",
  "CYANOCOBALAMIN": "시아노코발라민",
  "VITAMIN B12": "비타민비12",
  "THIAMINE": "티아민",
  "RIBOFLAVIN": "리보플라빈",
  "NIACINAMIDE": "니아신아미드",
  "PYRIDOXINE": "피리독신",
  "BIOTIN": "비오틴",
  "CALCIUM": "칼슘",
  "MAGNESIUM": "마그네슘",
  "ZINC": "아연",
  "IRON": "철분",
  "FERROUS SULFATE": "황산제일철",
  "FERROUS FUMARATE": "푸마르산철",

  // ── Ophthalmology / 안과 ────────────────────────────────────────────────
  "LATANOPROST": "라타노프로스트",
  "BIMATOPROST": "비마토프로스트",
  "TRAVOPROST": "트라보프로스트",
  "BRIMONIDINE": "브리모니딘",
  "DORZOLAMIDE": "도르졸라미드",

  // ── Dermatology / 피부과 ────────────────────────────────────────────────
  "TRETINOIN": "트레티노인",
  "ISOTRETINOIN": "이소트레티노인",
  "ADAPALENE": "아다팔렌",
  "BENZOYL PEROXIDE": "과산화벤조일",
  "MUPIROCIN": "무피로신",
  "PIMECROLIMUS": "피메크로리무스",
  "CALCIPOTRIOL": "칼시포트리올",
  "CLOBETASOL": "클로베타솔",
  "HALOBETASOL": "할로베타솔",

  // ── Urology / 비뇨기과 ──────────────────────────────────────────────────
  "TAMSULOSIN": "탐스로신",
  "ALFUZOSIN": "알푸조신",
  "DOXAZOSIN": "독사조신",
  "TERAZOSIN": "테라조신",
  "FINASTERIDE": "피나스테리드",
  "DUTASTERIDE": "두타스테리드",
  "SOLIFENACIN": "솔리페나신",
  "TOLTERODINE": "톨테로딘",
  "OXYBUTYNIN": "옥시부티닌",
  "MIRABEGRON": "미라베그론",

  // ── Psychiatry / 정신건강의학과 ─────────────────────────────────────────
  "LITHIUM": "리튬",
  "METHYLPHENIDATE": "메틸페니데이트",
  "ATOMOXETINE": "아토목세틴",
  "LISDEXAMFETAMINE": "리스덱삼페타민",
  "MODAFINIL": "모다피닐",
  "ARMODAFINIL": "아르모다피닐",
  "BUSPIRONE": "부스피론",
  "HYDROXYZINE": "하이드록시진",
  "DIPHENHYDRAMINE": "디펜하이드라민",

  // ── Hormonal Contraceptives / 피임약 ────────────────────────────────────
  "ETHINYL ESTRADIOL": "에티닐에스트라디올",
  "LEVONORGESTREL": "레보노르게스트렐",
  "DESOGESTREL": "데소게스트렐",
  "NORETHINDRONE": "노레틴드론",
  "DROSPIRENONE": "드로스피레논",
  "GESTODENE": "게스토덴",
  "CYPROTERONE": "시프로테론",

  // ── Vaccines & Biologics / 백신·바이오의약품 ────────────────────────────
  "RITUXIMAB": "리툭시맙",
  "TRASTUZUMAB": "트라스투주맙",
  "BEVACIZUMAB": "베바시주맙",
  "CETUXIMAB": "세툭시맙",
  "PEMBROLIZUMAB": "펨브롤리주맙",
  "NIVOLUMAB": "니볼루맙",
  "ATEZOLIZUMAB": "아테졸리주맙",
  "ETANERCEPT": "에타너셉트",
  "GOLIMUMAB": "골리무맙",
  "CERTOLIZUMAB": "세르톨리주맙",
  "SECUKINUMAB": "세쿠키누맙",
  "USTEKINUMAB": "우스테키누맙",
  "TOCILIZUMAB": "토실리주맙",
  "ABATACEPT": "아바타셉트",
  "BELIMUMAB": "벨리무맙",

  // ── Misc ─────────────────────────────────────────────────────────────────
  "MELATONIN": "멜라토닌",
  "CAFFEINE": "카페인",
  "PSEUDOEPHEDRINE": "슈도에페드린",
  "PHENYLEPHRINE": "페닐에프린",
  "CETIRIZINE": "세티리진",
  "LORATADINE": "로라타딘",
  "FEXOFENADINE": "펙소페나딘",
  "DESLORATADINE": "데스로라타딘",
  "LEVOCETIRIZINE": "레보세티리진",
  "AZELASTINE": "아젤라스틴",
  "CROMOGLICATE": "크로모글리케이트",
  "SODIUM CROMOGLICATE": "크로모글리케이트나트륨",
  "FLUORIDE": "불화물",
  "SODIUM FLUORIDE": "불화나트륨",
  "CHLORHEXIDINE": "클로르헥시딘",
  "POVIDONE IODINE": "포비돈요오드",
  "IODINE": "요오드",
  "HYDROGEN PEROXIDE": "과산화수소",
  "ZINC OXIDE": "산화아연",
  "DIMETHYL FUMARATE": "디메틸푸마레이트",
  "FINGOLIMOD": "핑골리모드",
  "NATALIZUMAB": "나탈리주맙",
  "INTERFERON BETA": "인터페론베타",
  "GLATIRAMER": "글라티라머",
  "RANIBIZUMAB": "라니비주맙",
  "AFLIBERCEPT": "애플리버셉트",
  "DARBEPOETIN": "다르베포에틴",
  "EPOETIN": "에포에틴",
  "FILGRASTIM": "필그라스팀",
  "PEGFILGRASTIM": "페그필그라스팀",
  "SOMATROPIN": "소마트로핀",
  "OCTREOTIDE": "옥트레오티드",
  "DESMOPRESSIN": "데스모프레신",
  "VASOPRESSIN": "바소프레신",
  "OXYTOCIN": "옥시토신",
  "CALCITONIN": "칼시토닌",
};

// ─── Lookup Helpers ────────────────────────────────────────────────────────────

/**
 * Find Korean name for a given English INN token.
 * Tries exact match first, then partial word match.
 */
export function toKoreanINN(englishToken: string): string | null {
  const upper = englishToken.trim().toUpperCase();

  // Exact match
  if (INN_KO[upper]) return INN_KO[upper];

  // Try removing parenthetical content and rematch
  const cleaned = upper.replace(/\([^)]*\)/g, "").trim();
  if (INN_KO[cleaned]) return INN_KO[cleaned];

  // Partial: check if any key is fully contained in the token
  for (const [en, ko] of Object.entries(INN_KO)) {
    if (upper.includes(en)) return ko;
  }

  // Partial: check if token is contained in any key
  for (const [en, ko] of Object.entries(INN_KO)) {
    if (en.includes(upper) && upper.length >= 5) return ko;
  }

  return null;
}

/**
 * Given an Ingredient_base (possibly multi-component, semicolon-separated),
 * return an array of Korean search terms — one per component.
 */
export function ingredientBaseToKorean(ingredientBase: string): {
  korean: string[];
  mapped: { en: string; ko: string | null }[];
} {
  const parts = ingredientBase
    .split(";")
    .map((p) => p.trim())
    .filter(Boolean);

  const mapped = parts.map((en) => ({ en, ko: toKoreanINN(en) }));
  const korean = mapped.filter((m) => m.ko !== null).map((m) => m.ko as string);

  return { korean, mapped };
}

/**
 * Get the primary Korean search term for an ingredient base.
 * Returns the first successfully mapped Korean name, or null.
 */
export function getPrimaryKorean(ingredientBase: string): string | null {
  const { korean } = ingredientBaseToKorean(ingredientBase);
  return korean[0] ?? null;
}
